package com.bridgepay.creditbureau.pool;

import jakarta.annotation.PostConstruct;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Static, in-memory pool of realistic profiles - a held-out 15% slice of the
 * Give Me Some Credit dataset, generated by scripts/generate_pool.py and
 * never touched by model training (spec section 6 - Mock Credit Bureau
 * Mechanics, and data/README.md for the exact split rule). Stateless: a new
 * applicant is deterministically hashed into this fixed list, so the same
 * applicant always gets the same row back, and correlated attributes
 * (income, debt ratio, utilization, credit lines) stay internally
 * consistent because whole rows are reused as-is rather than randomizing
 * individual fields.
 */
@Component
public class BureauPool {

    private static final String POOL_RESOURCE = "data/bureau-pool.csv";

    private List<BureauProfile> profiles;

    @PostConstruct
    void load() {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(
                new ClassPathResource(POOL_RESOURCE).getInputStream(), StandardCharsets.UTF_8))) {
            String headerLine = reader.readLine();
            if (headerLine == null) {
                throw new IllegalStateException(POOL_RESOURCE + " is empty");
            }
            Map<String, Integer> columnIndex = indexOf(headerLine.split(","));

            List<BureauProfile> loaded = new ArrayList<>();
            String line;
            while ((line = reader.readLine()) != null) {
                loaded.add(parseRow(line.split(","), columnIndex));
            }
            if (loaded.isEmpty()) {
                throw new IllegalStateException(POOL_RESOURCE + " contains no data rows");
            }
            profiles = List.copyOf(loaded);
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to load " + POOL_RESOURCE, ex);
        }
    }

    /**
     * Same applicant ID always maps to the same row - no per-request
     * re-roll, no true randomness.
     */
    public BureauProfile lookup(UUID applicantId) {
        int index = Math.floorMod(applicantId.hashCode(), profiles.size());
        return profiles.get(index);
    }

    int size() {
        return profiles.size();
    }

    private Map<String, Integer> indexOf(String[] header) {
        Map<String, Integer> index = new HashMap<>();
        for (int i = 0; i < header.length; i++) {
            index.put(header[i].trim(), i);
        }
        return index;
    }

    private BureauProfile parseRow(String[] cells, Map<String, Integer> columnIndex) {
        return new BureauProfile(
                Double.parseDouble(cells[columnIndex.get("RevolvingUtilizationOfUnsecuredLines")]),
                Integer.parseInt(cells[columnIndex.get("age")]),
                Integer.parseInt(cells[columnIndex.get("NumberOfTime30-59DaysPastDueNotWorse")]),
                Double.parseDouble(cells[columnIndex.get("DebtRatio")]),
                Double.parseDouble(cells[columnIndex.get("MonthlyIncome")]),
                Integer.parseInt(cells[columnIndex.get("NumberOfOpenCreditLinesAndLoans")]),
                Integer.parseInt(cells[columnIndex.get("NumberOfTimes90DaysLate")]),
                Integer.parseInt(cells[columnIndex.get("NumberRealEstateLoansOrLines")]),
                Integer.parseInt(cells[columnIndex.get("NumberOfTime60-89DaysPastDueNotWorse")]),
                Integer.parseInt(cells[columnIndex.get("NumberOfDependents")])
        );
    }
}
