apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - namespace.yaml
  - postgres.yaml
  - kafka.yaml
  - redis.yaml
  - keycloak.yaml
# These files live outside this folder (shared with docker-compose), so render
# with --load-restrictor LoadRestrictionsNone.
configMapGenerator:
  - name: postgres-init
    files:
      - ../../../postgres-init/01-create-keycloak-schema.sql
  - name: keycloak-realm
    files:
      - ../../../keycloak/bridgepay-realm.json
  - name: keycloak-theme
    files:
      - ../../../keycloak/themes/bridgepay/login/theme.properties
      - ../../../keycloak/themes/bridgepay/login/resources/css/bridgepay.css
      - ../../../keycloak/themes/bridgepay/login/resources/img/bridgepay-logo.svg
